### PR TITLE
Change new lines into double tabs for cleaner output - trivial

### PR DESCRIPTION
**Pull request by GrantSeltzer**
Addresses [Issue #17](https://github.com/dropbox/dbxcli/issues/17)

[Before](http://i.imgur.com/lW1WMiT.png) and [After](http://i.imgur.com/imhnWND.png)

Signed-off-by: Grantseltzer <grantseltzer@gmail.com>

### CODE REVIEW

**Comment by diwakergupta** [comment]
@GrantSeltzer  I can't see the after image, can you upload on imgur directly? Also, can you submit the CLA (I realize this is a "trivial" commit, but I would hope you'll send more PRs in future!)

**Comment by GrantSeltzer** [comment]
@diwakergupta I updated the link for the after photo. I filled out the CLA, and will definitely be submitting PR's, I'd really like to use this for dropbox but it has a lot of work to be done :grinning:

**Comment by GrantSeltzer** [comment]
Don't merge, forgot to make a new branch and just pushed for a separate PR. Fixing now

**Comment by GrantSeltzer** [comment]
Sorry for the clutter. Made new one for simplicity sake

**Pull request closed without merging**
