### PR TITLE
Add Makefile and gitignore

### PR DESCRIPTION
**Pull request by GrantSeltzer**
### Makefile
- binary option (including passing a version)
- clean
- all for both
- left install and test options empty, they should be added it in a later version of dbxcli when both are handled.

### .gitignore
- dbxcli binary shouldn't be committed to git.

### CODE REVIEW

**Comment by GrantSeltzer** [comment]
Not sure what caused that fail. @diwakergupta what do you think?

**Comment by diwakergupta** [comment]
Why do you want a Makefile? I don't want to add another dependency (make) when it isn't necessary (go tooling is more than sufficient).

I'm OK with adding a gitignore, but right now it adds an ignore for `dbxcli`, which would make it easier for a binary to accidentally get pushed into the repo.

Unless you have a strong rationale here, I'd prefer to just close out this PR, sorry!

**Comment by GrantSeltzer** [comment]
@diwakergupta That's 100% fine, I didn't have any strong rationale beyond thinking it may be useful.

**Comment by diwakergupta** [comment]
OK cool, thanks for understanding @GrantSeltzer.

FWIW build might have failed because the Makefile is confusing Travis's defaults. The current build process is actually just a wrapper around `go build` (we use `gox` for cross-compiling). See https://github.com/dropbox/dbxcli/blob/master/.travis.yml

**Pull request closed without merging**
