### PR TITLE
Use concurrent upload session in put cmd

### PR DESCRIPTION
**Pull request by rajatgoel**

### CODE REVIEW

**Comment by rajatgoel** [comment]
With a single worker - 

```
dbxcli put ~/Desktop/VSCode-darwin-universal.zip -w=1 uni.zip
Uploading 172 MiB/172 MiB

real	0m27.713s
user	0m0.716s
sys	0m1.206s
```

With 4 workers - 

```
dbxcli put ~/Desktop/VSCode-darwin-universal.zip -w=4 uni.zip
Uploading 172 MiB/172 MiB

real	0m14.128s
user	0m0.571s
sys	0m0.889s
```

A lot of time is spent in final commit. Need to take a look at that separately.

**Comment by arayiksmbatyan** [comment]
/root/.ottomatik_ops_dir/dbxcli put /root/videos/FILE20220304-091526-034985.mov -w=1 FILE20220304-091526-034985.mov 
Error: unknown shorthand flag: 'w' in -w=1

**Comment by arayiksmbatyan** [comment]
@rajatgoel it was compiled from the source. But the version is very old as v0.0.1

**Comment by arayiksmbatyan** [comment]
I use the last version 3.0.0 and have the same issue.
dropbox-issue

**Pull request merged**
